Update sap-hana-vm-arm.yaml for Azure Pipelines

diff --git a/DevOpsPipeline/sap-hana-vm-arm.yaml b/DevOpsPipeline/sap-hana-vm-arm.yaml
--- a/DevOpsPipeline/sap-hana-vm-arm.yaml
+++ b/DevOpsPipeline/sap-hana-vm-arm.yaml
@@ -525,13 +525,10 @@ stages:
         showWarnings: true
         failOnStderr: false
 
-- stage: Testing
+- stage: Performance_testing
   condition: eq(${{ parameters.hcmt }}, true)
   jobs:
   - job: HCMT
-    # timeoutInMinutes: 0
-    # cancelTimeoutInMinutes: 5
-    # HCMT runs very loooooooooooooooooong
     steps:
     - checkout: none
     - script: |
@@ -556,6 +553,28 @@ stages:
         ANSIBLE_DISPLAY_SKIPPED_HOSTS: False
         ANSIBLE_HOST_KEY_CHECKING: False
         ANSIBLE_SSH_HOST_KEY_CHECKING: False
+
+    - script: |
+        #!/bin/bash
+        green="\e[1;32m" ; reset="\e[0m" ; boldred="\e[1;31m"
+        cd $(Build.Repository.LocalPath)
+        if [ ! -f $(System.DefaultWorkingDirectory)/Inventory/${{ parameters.sid }}/hcmtresult-*.zip ]; then
+          echo "##vso[task.logissue type=error]No HCMT result found "
+          exit 2
+        else
+          echo -e "$green--- Adding HCMT test result to the inventory ---$reset"
+          mkdir -p $(System.DefaultWorkingDirectory)/Inventory/${{ parameters.sid }}
+          git checkout $(Build.SourceBranchName)
+          git config --global user.email "$(Build.RequestedForEmail)"
+          git config --global user.name "$(Build.RequestedFor)"
+          git add -f $(System.DefaultWorkingDirectory)/Inventory/${{ parameters.sid }}/hcmtresult-*.zip
+          git commit -m "Added HCMT test result $(Build.DefinitionName) [skip ci]"
+          git -c http.extraheader="AUTHORIZATION: bearer $(System.AccessToken)" push
+        fi
+      displayName: Write HCMT test result to inventory
+      env:
+        SYSTEM_ACCESSTOKEN:      $(System.AccessToken)
+      failOnStderr: false
 
 - stage: Cleanup
   condition: eq(${{ parameters.cleanup }}, true)
