Update sap-hana-vm-arm.yaml for Azure Pipelines

diff --git a/DevOpsPipeline/sap-hana-vm-arm.yaml b/DevOpsPipeline/sap-hana-vm-arm.yaml
--- a/DevOpsPipeline/sap-hana-vm-arm.yaml
+++ b/DevOpsPipeline/sap-hana-vm-arm.yaml
@@ -616,9 +616,24 @@ stages:
           echo $distro
           echo "##vso[task.setvariable variable=distro]$distro"
         fi
-        exit 0
-      displayName: Get private IP and Linux disrtibution for following ansible tasks 
+        echo -e "$green--- az login ---$reset"
+        az login --service-principal --username $(ARM_CLIENT_ID) --password $(ARM_CLIENT_SECRET) --tenant $(ARM_TENANT_ID)
+        return_code=$?
+        if [ 0 != $return_code ]; then
+          echo -e "$boldred--- Login failed ---$reset"
+          echo "##vso[task.logissue type=error]az login failed."
+          exit $return_code
+        fi
+        az account set --subscription $(ARM_SUBSCRIPTION_ID)
+      displayName: Get private IP, Linux distribution and perform az login
       failOnStderr: false
+      env:
+        ARM_SUBSCRIPTION_ID:     $(ARM_SUBSCRIPTION_ID)
+        ARM_CLIENT_ID:           $(ARM_CLIENT_ID)
+        ARM_CLIENT_SECRET:       $(ARM_CLIENT_SECRET)
+        ARM_TENANT_ID:           $(ARM_TENANT_ID)
+        SYSTEM_ACCESSTOKEN:      $(System.AccessToken)
+
     - task: Ansible@0
       displayName: 'Run Quality checks (Ansible)'
       inputs:
