Update sap-landing-zone.yaml for Azure Pipelines

diff --git a/DevOpsPipeline/sap-landing-zone.yaml b/DevOpsPipeline/sap-landing-zone.yaml
--- a/DevOpsPipeline/sap-landing-zone.yaml
+++ b/DevOpsPipeline/sap-landing-zone.yaml
@@ -97,6 +97,31 @@ stages:
   jobs:
   - job: Deploy_the_SAP_landing_zone
     steps:
+    - script: |
+        #!/bin/bash
+        green="\e[1;32m" ; reset="\e[0m" ; boldred="\e[1;31m"
+        echo -e "$green--- az login ---$reset"
+          az login --service-principal --username $(ARM_CLIENT_ID) --password $(ARM_CLIENT_SECRET) --tenant $(ARM_TENANT_ID)
+          return_code=$?
+          if [ 0 != $return_code ]; then
+            echo -e "$boldred--- Login failed ---$reset"
+            echo "##vso[task.logissue type=error]az login failed."
+            exit $return_code
+          fi
+        az account set --subscription $(ARM_SUBSCRIPTION_ID)
+        ARM_CLIENT_OBJECTID=$(az ad sp show --id $(ARM_CLIENT_ID) --query objectId)
+        echo "##vso[task.setvariable variable=ARM_CLIENT_OBJECTID]$ARM_CLIENT_OBJECTID"
+        echo -e "$green--- SPN Object Id is: $ARM_CLIENT_OBJECTID ---$reset"
+        exit $return_code
+      displayName: Get the objectId of the service principle for key vault and disk encryption set creation
+      condition: eq(${{ parameters.deploykeyvault }}, true)
+      env:
+        ARM_SUBSCRIPTION_ID:     $(ARM_SUBSCRIPTION_ID)
+        ARM_CLIENT_ID:           $(ARM_CLIENT_ID)
+        ARM_CLIENT_SECRET:       $(ARM_CLIENT_SECRET)
+        ARM_TENANT_ID:           $(ARM_TENANT_ID)
+      failOnStderr: false
+
     - task: AzureResourceManagerTemplateDeployment@3
       displayName: 'Deploy the SAP landing zone'
       inputs:
@@ -108,7 +133,7 @@ stages:
         location: '${{ parameters.location }}'
         templateLocation: 'Linked artifact'
         csmFile: $(System.DefaultWorkingDirectory)/ARM-Template/sap-landing-zone.json
-        overrideParameters: '-adminUsername "$(adminuser)" -adminPublicKey "$(pubsshkey)" -WindowsPassword "$(win-pw)" -SAPVNETNameAddressSpace "["${{ parameters.vnetrange }}"]" -SAPAdminSubnetAddressRange "${{ parameters.adminsubnetrange }}" -SAPSubnetAddressRange "${{ parameters.sapsubnetrange }}" -BastianSubnetAddressRange "${{ parameters.bastionsubnetrange }}" -VaultStorageType "${{ parameters.rsvtype }}" -VaultEnableCRR "${{ parameters.crr }}" -deployerpip "${{ parameters.deployerpip }}" -deploykeyvault "${{ parameters.deploykeyvault }}" '
+        overrideParameters: '-adminUsername "$(adminuser)" -adminPublicKey "$(pubsshkey)" -WindowsPassword "$(win-pw)" -SAPVNETNameAddressSpace "["${{ parameters.vnetrange }}"]" -SAPAdminSubnetAddressRange "${{ parameters.adminsubnetrange }}" -SAPSubnetAddressRange "${{ parameters.sapsubnetrange }}" -BastianSubnetAddressRange "${{ parameters.bastionsubnetrange }}" -VaultStorageType "${{ parameters.rsvtype }}" -VaultEnableCRR "${{ parameters.crr }}" -deployerpip "${{ parameters.deployerpip }}" -deploykeyvault "${{ parameters.deploykeyvault }}" -spnobjectid "$(ARM_CLIENT_OBJECTID)" '
         deploymentMode: 'Incremental'
         deploymentName: 'sap-landing-zone-$(Build.BuildId)'
         deploymentOutputs: 'arm_output'
